baseURL = 'https://hazemkrimi.tech'
languageCode = 'en'
title = 'Hazem Krimi'
paginate = 5
enableRobotsTXT = true
[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1
[services]
  [services.googleAnalytics]
    ID = 'G-FMD81GLKS3'
[taxonomies]
    tag = 'tags'
[params]
    formSpreeURL = 'https://formspree.io/f/xoqpgyge'
    dateFormat = '02 January 2006'
    defaultDescription = 'Personal website of Hazem Krimi'
    defaultKeywords = 'Hazem Krimi, Software Engineer, Software Developer, Full Stack Developer, JavaScript, TypeScript, React, Node.js, Scala, Kotlin, Corda, SQL, GraphQL, MongoDB'
    [params.author]
        email = 'me@hazemkrimi.tech'
        name = 'Hazem Krimi'
[module]
[menu]
    [[menu.main]]
        name = 'Home'
        url = '/'
        weight = 1
    [[menu.main]]
        name = 'About'
        url = '/about'
        weight = 2
    [[menu.main]]
        name = 'Projects'
        url = '/projects'
        weight = 3
    [[menu.main]]
        name = 'Blog'
        url = '/blog'
        weight = 4
    [[menu.main]]
        name = 'Contact'
        url = '/contact'
        weight = 5
[[deployment.matchers]]
    # Cache static assets for 1 year.
    pattern = "^.+\\.(js|css|svg|ttf)$"
    cacheControl = "max-age=31536000, no-transform, public"
    gzip = true
[[deployment.matchers]]
    pattern = "^.+\\.(gif|png|jpg|webp)$"
    cacheControl = "max-age=31536000, no-transform, public"
    gzip = false
[[deployment.matchers]]
    # Set custom content type for /sitemap.xml
    pattern = "^sitemap\\.xml$"
    contentType = "application/xml"
    gzip = true
[[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json)$"
    gzip = true
