languageCode = 'en-us'
title = 'Hazem Krimi'
[params]
    formSpreeURL = 'https://formspree.io/f/xoqpgyge'
[module]
[menu]
    [[menu.main]]
        name = 'Home'
        url = '/'
        weight = 1
    [[menu.main]]
        name = 'About'
        url = '/about'
        weight = 2
    [[menu.main]]
        name = 'Projects'
        url = '/projects'
        weight = 3
    [[menu.main]]
        name = 'Blog'
        url = '/blog'
        weight = 4
    [[menu.main]]
        name = 'Contact'
        url = '/contact'
        weight = 5
