languageCode = 'en-us'
title = 'Hazem Krimi'
paginate = 5
enableRobotsTXT = true
[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1
[taxonomies]
    tag = 'tags'
[params]
    formSpreeURL = 'https://formspree.io/f/xoqpgyge'
    dateFormat = '02 January 2006'
    [params.author]
        email = 'me@hazemkrimi.tech'
        name = 'Hazem Krimi'
[module]
[menu]
    [[menu.main]]
        name = 'Home'
        url = '/'
        weight = 1
    [[menu.main]]
        name = 'About'
        url = '/about'
        weight = 2
    [[menu.main]]
        name = 'Projects'
        url = '/projects'
        weight = 3
    [[menu.main]]
        name = 'Blog'
        url = '/blog'
        weight = 4
    [[menu.main]]
        name = 'Contact'
        url = '/contact'
        weight = 5
