baseURL = 'https://hazemkrimi.tech'
languageCode = 'en'
title = 'Hazem Krimi'
[pagination]
    pagerSize = 5
enableRobotsTXT = true
[outputs]
    home = ['html', 'rss']
    section = ['html', 'rss']
[sitemap]
    changeFreq = ''
    filename = 'sitemap.xml'
    priority = -1
[taxonomies]
    tag = 'tags'
[params]
    dateFormat = '02 January 2006'
    defaultDescription = 'Personal website of Hazem Krimi'
    defaultKeywords = ['Hazem Krimi', 'Software Engineer', 'Software Developer', 'Full Stack Developer', 'JavaScript', 'TypeScript', 'React.js', 'Node.js', 'Go', 'Golang', 'Scala', 'Kotlin', 'SQL', 'GraphQL', 'MongoDB', 'Corda']
    [params.author]
        email = 'me@hazemkrimi.tech'
        name = 'Hazem Krimi'
[module]
[menu]
    [[menu.main]]
        name = 'Home'
        url = '/'
        weight = 1
    [[menu.main]]
        name = 'About'
        url = '/about'
        weight = 2
    [[menu.main]]
        name = 'Projects'
        url = '/projects'
        weight = 3
    [[menu.main]]
        name = 'Blog'
        url = '/blog'
        weight = 4
    [[menu.main]]
        name = 'CV'
        url = '/curriculum-vitae.pdf'
        weight = 5
[[deployment.matchers]]
    pattern = "^.+\\.(js|css|svg|ttf)$"
    cacheControl = "max-age=31536000, no-transform, public"
    gzip = true
[[deployment.matchers]]
    pattern = "^.+\\.(gif|png|jpg|webp)$"
    cacheControl = "max-age=31536000, no-transform, public"
    gzip = false
[[deployment.matchers]]
    pattern = "^sitemap\\.xml$"
    contentType = "application/xml"
    gzip = true
[[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json)$"
    gzip = true
